Question.create(:prompt => 'revocar', :answer => 'to revoke, to repeal')
Question.create(:prompt => 'revolver', :answer => 'to revolve, to turn around, to turn over, to turn upside down')
Question.create(:prompt => 'robar', :answer => 'to rob, to steal')
Question.create(:prompt => 'rogar', :answer => 'to supplicate, to ask, to ask for, to request, to beg, to pray')
Question.create(:prompt => 'romper', :answer => 'to break, to shatter, to tear')
Question.create(:prompt => 'saber', :answer => 'to know, to know how')
Question.create(:prompt => 'sacar', :answer => 'to take out, to get')
Question.create(:prompt => 'sacudir', :answer => 'to shake, to jerk, to jolt')
Question.create(:prompt => 'salir', :answer => 'to go out, to leave')
Question.create(:prompt => 'saltar', :answer => 'to jump, to leap, to hop, to spring')
Question.create(:prompt => 'saludar', :answer => 'to greet, to salute')
Question.create(:prompt => 'satisfacer', :answer => 'to satisfy')
Question.create(:prompt => 'secar', :answer => 'to dry, to wipe dry')
Question.create(:prompt => 'secarse', :answer => 'to dry oneself')
Question.create(:prompt => 'seguir', :answer => 'to follow, to pursue, to continue')
Question.create(:prompt => 'se?alar', :answer => 'to signal, to indicate, to point out, to show')
Question.create(:prompt => 'sentarse', :answer => 'to sit down')
Question.create(:prompt => 'sentir', :answer => 'to feel sorry, to regret, to feel')
Question.create(:prompt => 'sentirse', :answer => 'to feel (well, ill)')
Question.create(:prompt => 'separar', :answer => 'to separate, to detach, to sort, to set apart')
Question.create(:prompt => 'ser', :answer => 'to be')
Question.create(:prompt => 'servir', :answer => 'to serve')
Question.create(:prompt => 'socorrer', :answer => 'to help, to aid, to assist, to succor')
Question.create(:prompt => 'sofocar', :answer => 'to choke, to smother, to suffocate, to stifle')
Question.create(:prompt => 'soler', :answer => 'to be accustomed to, to be in the habit of, to have the custom of')
Question.create(:prompt => 'sollozar', :answer => 'to sob, to whimper')
Question.create(:prompt => 'someter', :answer => 'to subdue, to subject, to surrender, to submit')
Question.create(:prompt => 'sonar', :answer => 'to ring, to echo, to resound, to sound')
Question.create(:prompt => 'soplar', :answer => 'to blow, to blow out')
Question.create(:prompt => 'sorprender', :answer => 'to surprise, to astonish')
Question.create(:prompt => 'sospechar', :answer => 'to suspect')
Question.create(:prompt => 'sostener', :answer => 'to sustain, to support, to maintain, to uphold')
Question.create(:prompt => 'subir', :answer => 'to go up, to come up, to climb, to rise, to mount, to get on (a train, bus, etc.)')
Question.create(:prompt => 'subrayar', :answer => 'to underline, to underscore, to emphasize')
Question.create(:prompt => 'subscribir', :answer => 'to subscribe, to agree with, to sign')
Question.create(:prompt => 'suceder', :answer => 'to happen')
Question.create(:prompt => 'sufrir', :answer => 'to suffer, to endure, to bear up, to undergo')
Question.create(:prompt => 'sugerir', :answer => 'to hint, to insinuate, to suggest')
Question.create(:prompt => 'sumergir', :answer => 'to submerge, to plunge, to immerse, to sink')
Question.create(:prompt => 'suponer', :answer => 'to suppose, to assume')
Question.create(:prompt => 'suprimir', :answer => 'to suppress, to abolish, to cancel (in mathematics), to eliminate')
Question.create(:prompt => 'surgir', :answer => 'to surge, to appear, to spout, to spurt')
Question.create(:prompt => 'suspirar', :answer => 'to sigh')
Question.create(:prompt => 'ta?er', :answer => 'to pluck, to play (a stringed instrument)')
Question.create(:prompt => 'telefonear', :answer => 'to telephone')
Question.create(:prompt => 'telegrafiar', :answer => 'to telegraph, to cable')
Question.create(:prompt => 'temblar', :answer => 'to tremble, to quake, to quiver, to shake, to shiver')
Question.create(:prompt => 'temer', :answer => 'to fear, to dread')
Question.create(:prompt => 'tender', :answer => 'to extend, to offer, to stretch, to spread out, to hang out (washing)')
Question.create(:prompt => 'tener', :answer => 'to have, to hold')
Question.create(:prompt => 'tentar', :answer => 'to examine by touch, to feel with the fingers, to attempt, to try')
Question.create(:prompt => 'terminar', :answer => 'to end, to terminate, to finish')
Question.create(:prompt => 'venir', :answer => 'to come')
Question.create(:prompt => 'tirar', :answer => 'to pull, to draw, to pitch (a ball), to shoot (a gun), to throw, to fling')
Question.create(:prompt => 'ver', :answer => 'to see')
Question.create(:prompt => 'tocar', :answer => 'to play (a musical instrument), to touch')
Question.create(:prompt => 'tomar', :answer => 'to take, to have (something to eat or to drink)')
Question.create(:prompt => 'zurcir', :answer => 'to darn, to mend')
Question.create(:prompt => 'tostar', :answer => 'to toast, to tan, to roast (coffee)')
Question.create(:prompt => 'trabajar', :answer => 'to work, to labor')
Question.create(:prompt => 'traducir', :answer => 'to translate')
Question.create(:prompt => 'traer', :answer => 'to bring')
Question.create(:prompt => 'tratar', :answer => 'to try, to treat a subject')
Question.create(:prompt => 'tropezar', :answer => 'to stumble, to blunder')
Question.create(:prompt => 'unir', :answer => 'to connect, to unite, to join, to bind, to attach')
Question.create(:prompt => 'usar', :answer => 'to use, to employ, to wear')
Question.create(:prompt => 'utilizar', :answer => 'to utilize')
Question.create(:prompt => 'vaciar', :answer => 'to empty')
Question.create(:prompt => 'valer', :answer => 'to be worth')
Question.create(:prompt => 'velar', :answer => 'to stay awake, to guard, to watch over')
Question.create(:prompt => 'vencer', :answer => 'to conquer, to overcome, to defeat')
Question.create(:prompt => 'vender', :answer => 'to sell')
Question.create(:prompt => 'vestirse', :answer => 'to dress oneself, to get dressed')
Question.create(:prompt => 'viajar', :answer => 'to travel')
Question.create(:prompt => 'vigilar', :answer => 'to watch (over), to keep guard, to look out for')
Question.create(:prompt => 'visitar', :answer => 'to visit')
Question.create(:prompt => 'vivir', :answer => 'to live')
Question.create(:prompt => 'volar', :answer => 'to fly')
Question.create(:prompt => 'volver', :answer => 'to return, to go back')
Question.create(:prompt => 'votar', :answer => 'to vote, to vow')
Question.create(:prompt => 'yacer', :answer => 'to lie down, to be lying down, to lie in a grave')
Question.create(:prompt => 'zumbar', :answer => 'to buzz, to hum, to flutter around')
Question.create(:prompt => 'mostrar', :answer => 'to show, to point out')
Question.create(:prompt => 'mover', :answer => 'to move, to persuade, to excite')
Question.create(:prompt => 'mudarse', :answer => 'to change one\'s clothes, to change one\'s place of residence, to move')
Question.create(:prompt => 'nacer', :answer => 'to be born')
Question.create(:prompt => 'nadar', :answer => 'to swim')
Question.create(:prompt => 'navegar', :answer => 'to navigate, to sail')
Question.create(:prompt => 'necesitar', :answer => 'to need')
Question.create(:prompt => 'negar', :answer => 'to deny')
Question.create(:prompt => 'nevar', :answer => 'to snow')
Question.create(:prompt => 'obedecer', :answer => 'to obey')
Question.create(:prompt => 'observar', :answer => 'to observe')
Question.create(:prompt => 'obtener', :answer => 'to obtain, to get')
Question.create(:prompt => 'ocultarse', :answer => 'to hide oneself')
Question.create(:prompt => 'ocupar', :answer => 'to occupy')
Question.create(:prompt => 'ocurrir', :answer => 'to occur, to happen')
Question.create(:prompt => 'ofrecer', :answer => 'to offer')
Question.create(:prompt => 'o?r', :answer => 'to hear')
Question.create(:prompt => 'oler', :answer => 'to smell, to scent')
Question.create(:prompt => 'olvidar', :answer => 'to forget')
Question.create(:prompt => 'oponer', :answer => 'to oppose')
Question.create(:prompt => 'ordenar', :answer => 'to order, to command, to put in order, to arrange')
Question.create(:prompt => 'organizar', :answer => 'to organize, to arrange, to set up')
Question.create(:prompt => 'osar', :answer => 'to dare, to venture')
Question.create(:prompt => 'pagar', :answer => 'to pay')
Question.create(:prompt => 'parar', :answer => 'to stop (someone or something)')
Question.create(:prompt => 'pararse', :answer => 'to stop (oneself)')
Question.create(:prompt => 'parecer', :answer => 'to seem, to appear')
Question.create(:prompt => 'parecerse', :answer => 'to resemble each other, to look alike')
Question.create(:prompt => 'partir', :answer => 'to leave, to depart, to divide, to split')
Question.create(:prompt => 'pasar', :answer => 'to pass (by), to happen, to spend (time)')
Question.create(:prompt => 'pasearse', :answer => 'to take a walk, to parade')
Question.create(:prompt => 'pedir', :answer => 'to ask for, to request')
Question.create(:prompt => 'pegar', :answer => 'to beat, to hit, to slap, to stick, to glue, to paste')
Question.create(:prompt => 'peinarse', :answer => 'to comb one\'s hair')
Question.create(:prompt => 'pensar', :answer => 'to think')
Question.create(:prompt => 'percibir', :answer => 'to perceive')
Question.create(:prompt => 'perder', :answer => 'to lose')
Question.create(:prompt => 'perdonar', :answer => 'to pardon, to forgive, to excuse')
Question.create(:prompt => 'permitir', :answer => 'to permit, to admit, to allow, to grant')
Question.create(:prompt => 'pertenecer', :answer => 'to pertain, to appertain, to belong')
Question.create(:prompt => 'pintar', :answer => 'to paint')
Question.create(:prompt => 'pintarse', :answer => 'to make up (one\s face), to tint, to color (one\s hair, lips, etc.)')
Question.create(:prompt => 'pisar', :answer => 'to tread (on), to step on, to trample')
Question.create(:prompt => 'placer', :answer => 'to gratify, to humor, to please')
Question.create(:prompt => 'platicar', :answer => 'to chat, to talk over, to discuss')
Question.create(:prompt => 'poder', :answer => 'to be able, can')
Question.create(:prompt => 'poner', :answer => 'to put, to place')
Question.create(:prompt => 'ponerse', :answer => 'to put on (clothing), to become, to set (of sun)')
Question.create(:prompt => 'poseer', :answer => 'to possess, to own')
Question.create(:prompt => 'practicar', :answer => 'to practice')
Question.create(:prompt => 'predecir', :answer => 'to predict, to forecast, to foretell')
Question.create(:prompt => 'predicar', :answer => 'to preach')
Question.create(:prompt => 'preferir', :answer => 'to prefer')
Question.create(:prompt => 'preguntar', :answer => 'to ask, to inquire, to prompt')
Question.create(:prompt => 'preocuparse', :answer => 'to be concerned, to worry, to be worried')
Question.create(:prompt => 'preparar', :answer => 'to prepare')
Question.create(:prompt => 'prepararse', :answer => 'to be prepared, to get ready, to prepare oneself')
Question.create(:prompt => 'presentar', :answer => 'to present, to display, to show, to introduce')
Question.create(:prompt => 'prestar', :answer => 'to lend')
Question.create(:prompt => 'principiar', :answer => 'to begin')
Question.create(:prompt => 'probar', :answer => 'to test, to prove, to try, to try on')
Question.create(:prompt => 'probarse', :answer => 'to try on (clothes)')
Question.create(:prompt => 'proclamar', :answer => 'to proclaim, to promulgate')
Question.create(:prompt => 'producir', :answer => 'to produce, to cause')
Question.create(:prompt => 'prohibir', :answer => 'to prohibit, to forbid')
Question.create(:prompt => 'pronunciar', :answer => 'to pronounce')
Question.create(:prompt => 'proteger', :answer => 'to protect')
Question.create(:prompt => 'pulir', :answer => 'to polish')
Question.create(:prompt => 'quedarse', :answer => 'to remain, to stay')
Question.create(:prompt => 'quejarse', :answer => 'to complain, to grumble')
Question.create(:prompt => 'quemar', :answer => 'to burn, to fire')
Question.create(:prompt => 'querer', :answer => 'to want, to wish')
Question.create(:prompt => 'quitarse', :answer => 'to take off (clothing), to remove oneself, to withdraw')
Question.create(:prompt => 'raer', :answer => 'to scrape, to rub off, to erase, to wipe out')
Question.create(:prompt => 'realizar', :answer => 'to realize, to carry out, to fulfill')
Question.create(:prompt => 'recibir', :answer => 'to receive, to get')
Question.create(:prompt => 'recoger', :answer => 'to pick (up), to gather, to harvest')
Question.create(:prompt => 'recomendar', :answer => 'to recommend, to commend, to advise')
Question.create(:prompt => 'reconocer', :answer => 'to recognize, to acknowledge, to be grateful for')
Question.create(:prompt => 'recordar', :answer => 'to remember, to recall, to remind')
Question.create(:prompt => 'referir', :answer => 'to refer, to relate')
Question.create(:prompt => 'regalar', :answer => 'to give as a present, to make a present of, to give as a gift')
Question.create(:prompt => 'regar', :answer => 'to water, to irrigate, to sprinkle')
Question.create(:prompt => 'regresar', :answer => 'to return, to go back, to regress')
Question.create(:prompt => 'rellenar', :answer => 'to refill, to fill again, to stuff')
Question.create(:prompt => 'remitir', :answer => 'to remit, to forward, to transmit')
Question.create(:prompt => 'reparar', :answer => 'to mend, to repair, to notice, to observe')
Question.create(:prompt => 'repartir', :answer => 'to distribute, to deal cards')
Question.create(:prompt => 'repetir', :answer => 'to repeat')
Question.create(:prompt => 'resolver', :answer => 'to resolve, to solve (a problem)')
Question.create(:prompt => 'responder', :answer => 'to answer, to reply, to respond')
Question.create(:prompt => 'retirar', :answer => 'to retire, to withdraw')
Question.create(:prompt => 'retrasar', :answer => 'to delay, to retard')
Question.create(:prompt => 'reunirse', :answer => 'to assemble, to get together, to meet, to gather')
Question.create(:prompt => 'escuchar', :answer => 'to listen (to)')
Question.create(:prompt => 'dar', :answer => 'to give')
Question.create(:prompt => 'esparcir', :answer => 'to scatter, to spread')
Question.create(:prompt => 'esperar', :answer => 'to expect, to hope, to wait (for)')
Question.create(:prompt => 'esquiar', :answer => 'to ski')
Question.create(:prompt => 'establecer', :answer => 'to establish')
Question.create(:prompt => 'estar', :answer => 'to be')
Question.create(:prompt => 'gemir', :answer => 'to grieve, to groan, to moan')
Question.create(:prompt => 'estimar', :answer => 'to estimate, to esteem, to respect, to value')
Question.create(:prompt => 'estudiar', :answer => 'to study')
Question.create(:prompt => 'exigir', :answer => 'to demand, to urge, to require')
Question.create(:prompt => 'explicar', :answer => 'to explain')
Question.create(:prompt => 'expresar', :answer => 'to express')
Question.create(:prompt => 'fabricar', :answer => 'to fabricate, to manufacture')
Question.create(:prompt => 'gobernar', :answer => 'to govern, to rule')
Question.create(:prompt => 'gozar', :answer => 'to enjoy')
Question.create(:prompt => 'faltar', :answer => 'to be lacking, to be wanting, to lack, to miss, to need')
Question.create(:prompt => 'felicitar', :answer => 'to congratulate, to felicitate')
Question.create(:prompt => 'festejar', :answer => 'to feast, to entertain, to celebrate')
Question.create(:prompt => 'fiar', :answer => 'to confide, to trust')
Question.create(:prompt => 'fijarse', :answer => 'to take notice, to pay attention, to settle')
Question.create(:prompt => 'fingir', :answer => 'to feign, to pretend')
Question.create(:prompt => 'firmar', :answer => 'to sign')
Question.create(:prompt => 'formar', :answer => 'to form, to shape')
Question.create(:prompt => 'fregar', :answer => 'to wash dishes, to scrub')
Question.create(:prompt => 'fumar', :answer => 'to smoke')
Question.create(:prompt => 'funcionar', :answer => 'to function, to run (machine)')
Question.create(:prompt => 'ganar', :answer => 'to earn, to gain, to win')
Question.create(:prompt => 'gastar', :answer => 'to spend (money), to wear out, to waste')
Question.create(:prompt => 'gritar', :answer => 'to shout, to scream, to shriek, to cry out')
Question.create(:prompt => 'guiar', :answer => 'to lead, to guide')
Question.create(:prompt => 'gustar', :answer => 'to be pleasing (to), to like')
Question.create(:prompt => 'haber', :answer => 'to have (as an auxiliary, helping verb to form the compound tenses)')
Question.create(:prompt => 'habitar', :answer => 'to inhabit, to dwell, to live, to reside')
Question.create(:prompt => 'hablar', :answer => 'to talk, to speak')
Question.create(:prompt => 'hacer', :answer => 'to do, to make')
Question.create(:prompt => 'hallar', :answer => 'to find, to discover, to locate')
Question.create(:prompt => 'helar', :answer => 'to freeze')
Question.create(:prompt => 'heredar', :answer => 'to inherit')
Question.create(:prompt => 'herir', :answer => 'to harm, to hurt, to wound')
Question.create(:prompt => 'huir', :answer => 'to escape, to flee, to run away, to slip away')
Question.create(:prompt => 'ignorar', :answer => 'to be ignorant of, not to know')
Question.create(:prompt => 'impedir', :answer => 'to hinder, to impede, to prevent')
Question.create(:prompt => 'importar', :answer => 'to matter, to be important')
Question.create(:prompt => 'imprimir', :answer => 'to imprint, to impress, to print, to fix in the mind')
Question.create(:prompt => 'incluir', :answer => 'to include, to enclose')
Question.create(:prompt => 'indicar', :answer => 'to indicate, to point out')
Question.create(:prompt => 'inducir', :answer => 'to induce, to influence, to persuade')
Question.create(:prompt => 'influir', :answer => 'to influence')
Question.create(:prompt => 'informarse', :answer => 'to inform oneself, to find out')
Question.create(:prompt => 'inscribir', :answer => 'to inscribe, to record, to register')
Question.create(:prompt => 'inscribirse', :answer => 'to enroll, to register')
Question.create(:prompt => 'insistir', :answer => 'to insist, to persist')
Question.create(:prompt => 'interesarse', :answer => 'to be interested in')
Question.create(:prompt => 'introducir', :answer => 'to introduce')
Question.create(:prompt => 'invitar', :answer => 'to invite')
Question.create(:prompt => 'ir', :answer => 'to go')
Question.create(:prompt => 'irse', :answer => 'to go away')
Question.create(:prompt => 'jugar', :answer => 'to play (a game, sport)')
Question.create(:prompt => 'juntar', :answer => 'to join, to unite, to connect')
Question.create(:prompt => 'jurar', :answer => 'to swear, to take an oath')
Question.create(:prompt => 'juzgar', :answer => 'to judge')
Question.create(:prompt => 'lanzar', :answer => 'to throw, to hurl, to fling, to launch')
Question.create(:prompt => 'lastimarse', :answer => 'to hurt oneself, to feel sorry for, to complain, to regret')
Question.create(:prompt => 'lavar', :answer => 'to wash')
Question.create(:prompt => 'lavarse', :answer => 'to wash oneself')
Question.create(:prompt => 'leer', :answer => 'to read')
Question.create(:prompt => 'levantar', :answer => 'to lift, to raise')
Question.create(:prompt => 'levantarse', :answer => 'to get up, to rise')
Question.create(:prompt => 'limpiar', :answer => 'to clean')
Question.create(:prompt => 'limpiarse', :answer => 'to clean oneself')
Question.create(:prompt => 'llamar', :answer => 'to call, to name')
Question.create(:prompt => 'llamarse', :answer => 'to call oneself, to be named')
Question.create(:prompt => 'llegar', :answer => 'to arrive')
Question.create(:prompt => 'llenar', :answer => 'to fill')
Question.create(:prompt => 'llevar', :answer => 'to carry (away), to take (away), to wear')
Question.create(:prompt => 'llorar', :answer => 'to weep, to cry, to whine')
Question.create(:prompt => 'llover', :answer => 'to rain')
Question.create(:prompt => 'luchar', :answer => 'to fight, to strive, to struggle, to wrestle')
Question.create(:prompt => 'maldecir', :answer => 'to curse')
Question.create(:prompt => 'manejar', :answer => 'to manage, to handle, to drive, to operate (a vehicle)')
Question.create(:prompt => 'mantener', :answer => 'to maintain, to keep up, to support, to provide for')
Question.create(:prompt => 'marcar', :answer => 'to mark, to note, to observe')
Question.create(:prompt => 'marchar', :answer => 'to walk, to march, to function (machine), to run (machine)')
Question.create(:prompt => 'marcharse', :answer => 'to go away, to leave')
Question.create(:prompt => 'matar', :answer => 'to kill')
Question.create(:prompt => 'medir', :answer => 'to measure, to weigh, to scan (verses)')
Question.create(:prompt => 'mejorar', :answer => 'to improve')
Question.create(:prompt => 'mencionar', :answer => 'to mention')
Question.create(:prompt => 'mentir', :answer => 'to lie, to tell a lie')
Question.create(:prompt => 'merecer', :answer => 'to merit, to deserve')
Question.create(:prompt => 'mirar', :answer => 'to look, to look at, to watch')
Question.create(:prompt => 'mirarse', :answer => 'to look at oneself, to look at each other (uno a otro, unos a otros)')
Question.create(:prompt => 'mojarse', :answer => 'to get wet, to wet oneself')
Question.create(:prompt => 'montar', :answer => 'to mount, to go up, to climb, to get on, to wind (a watch)')
Question.create(:prompt => 'morder', :answer => 'to bite')
Question.create(:prompt => 'morir', :answer => 'to die')
Question.create(:prompt => 'componer', :answer => 'to compose')
Question.create(:prompt => 'comprar', :answer => 'to buy, to purchase')
Question.create(:prompt => 'comprender', :answer => 'to understand')
Question.create(:prompt => 'conducir', :answer => 'to lead, to conduct, to drive')
Question.create(:prompt => 'confesar', :answer => 'to confess')
Question.create(:prompt => 'conocer', :answer => 'to know, to be acquainted with')
Question.create(:prompt => 'conseguir', :answer => 'to attain, to get, to obtain')
Question.create(:prompt => 'constituir', :answer => 'to constitute, to make up')
Question.create(:prompt => 'construir', :answer => 'to construct, to build')
Question.create(:prompt => 'contar', :answer => 'to count, to relate, to tell')
Question.create(:prompt => 'contener', :answer => 'to contain, to hold')
Question.create(:prompt => 'contestar', :answer => 'to answer, to reply')
Question.create(:prompt => 'continuar', :answer => 'to continue')
Question.create(:prompt => 'contribuir', :answer => 'to contribute')
Question.create(:prompt => 'convencer', :answer => 'to convince')
Question.create(:prompt => 'convenir', :answer => 'to agree, to convene')
Question.create(:prompt => 'convertir', :answer => 'to convert')
Question.create(:prompt => 'convocar', :answer => 'to call together, to convene, to convoke, to summon')
Question.create(:prompt => 'corregir', :answer => 'to correct')
Question.create(:prompt => 'correr', :answer => 'to run, to race, to flow')
Question.create(:prompt => 'cortar', :answer => 'to cut, to cut off, to cut out')
Question.create(:prompt => 'costar', :answer => 'to cost')
Question.create(:prompt => 'crecer', :answer => 'to grow')
Question.create(:prompt => 'creer', :answer => 'to believe')
Question.create(:prompt => 'criar', :answer => 'to breed, to raise, to bring up (rear)')
Question.create(:prompt => 'cruzar', :answer => 'to cross')
Question.create(:prompt => 'cubrir', :answer => 'to cover')
Question.create(:prompt => 'cuidarse', :answer => 'to take care of oneself')
Question.create(:prompt => 'deber', :answer => 'to owe, must, ought')
Question.create(:prompt => 'decidir', :answer => 'to decide')
Question.create(:prompt => 'decir', :answer => 'to say, to tell')
Question.create(:prompt => 'declarar', :answer => 'to declare')
Question.create(:prompt => 'dedicarse', :answer => 'to devote oneself')
Question.create(:prompt => 'defender', :answer => 'to defend')
Question.create(:prompt => 'dejar', :answer => 'to let, to permit, to allow, to leave')
Question.create(:prompt => 'delinquir', :answer => 'to be delinquent, to violate the law')
Question.create(:prompt => 'demostrar', :answer => 'to demonstrate, to prove')
Question.create(:prompt => 'denunciar', :answer => 'to denounce')
Question.create(:prompt => 'depender', :answer => 'to depend')
Question.create(:prompt => 'derribar', :answer => 'to knock down, to overthrow, to tear down, to throw down')
Question.create(:prompt => 'desayunarse', :answer => 'to breakfast, to have breakfast')
Question.create(:prompt => 'descansar', :answer => 'to rest')
Question.create(:prompt => 'describir', :answer => 'to describe, to delineate')
Question.create(:prompt => 'descubrir', :answer => 'to discover')
Question.create(:prompt => 'desear', :answer => 'to desire, to wish, to want')
Question.create(:prompt => 'deshacer', :answer => 'to undo, to destroy, to take apart')
Question.create(:prompt => 'despedirse', :answer => 'to take leave of, to say good-bye to')
Question.create(:prompt => 'despegar', :answer => 'to detach, to unglue, to unstuck, to take off (airplane)')
Question.create(:prompt => 'desperezarse', :answer => 'to stretch oneself, to stretch one\'s arms and legs')
Question.create(:prompt => 'despertarse', :answer => 'to wake up oneself')
Question.create(:prompt => 'destruir', :answer => 'to destroy')
Question.create(:prompt => 'desvestirse', :answer => 'to undress oneself, to get undressed')
Question.create(:prompt => 'detener', :answer => 'to stop (someone or something), to detain')
Question.create(:prompt => 'detenerse', :answer => 'to stop (oneself)')
Question.create(:prompt => 'devolver', :answer => 'to return (an object), to refund, to give back')
Question.create(:prompt => 'dibujar', :answer => 'to design, to draw, to sketch')
Question.create(:prompt => 'dirigir', :answer => 'to direct')
Question.create(:prompt => 'disculparse', :answer => 'to apologize, to excuse (oneself)')
Question.create(:prompt => 'discutir', :answer => 'to discuss')
Question.create(:prompt => 'dispensar', :answer => 'to excuse, to dispense, to distribute, to exempt')
Question.create(:prompt => 'distinguir', :answer => 'to distinguish')
Question.create(:prompt => 'divertirse', :answer => 'to have a good time, to enjoy oneself')
Question.create(:prompt => 'divorciarse', :answer => 'to be (get) divorced')
Question.create(:prompt => 'doler', :answer => 'to ache, to pain, to hurt, to cause grief, to cause regret')
Question.create(:prompt => 'dormir', :answer => 'to sleep')
Question.create(:prompt => 'ducharse', :answer => 'to take a shower, to shower oneself')
Question.create(:prompt => 'dudar', :answer => 'to doubt')
Question.create(:prompt => 'echar', :answer => 'to cast, to fling, to hurt, to pitch, to throw')
Question.create(:prompt => 'ejecutar', :answer => 'to execute, to carry out, to perform')
Question.create(:prompt => 'ejercer', :answer => 'to exercise, to practice (a professional)')
Question.create(:prompt => 'elegir', :answer => 'to elect, to select, to choose')
Question.create(:prompt => 'embeber', :answer => 'to soak in, to soak up, to suck in, to imbibe')
Question.create(:prompt => 'empezar', :answer => 'to begin, to start')
Question.create(:prompt => 'emplear', :answer => 'to employ, to use')
Question.create(:prompt => 'encender', :answer => 'to incite, to inflame, to kindle, to light')
Question.create(:prompt => 'encerrar', :answer => 'to enclose, to lock up, to confine')
Question.create(:prompt => 'celebrar', :answer => 'to celebrate')
Question.create(:prompt => 'encontrar', :answer => 'to meet, to encounter, to find')
Question.create(:prompt => 'enfadarse', :answer => 'to become angry')
Question.create(:prompt => 'enfermarse', :answer => 'to get sick, to fall sick, to become sick, to fall ill, to become ill')
Question.create(:prompt => 'enojarse', :answer => 'to become angry, to get angry, to get cross')
Question.create(:prompt => 'entender', :answer => 'to understand')
Question.create(:prompt => 'entrar', :answer => 'to enter, to go (in), to come (in)')
Question.create(:prompt => 'entregar', :answer => 'to deliver, to hand over, to give')
Question.create(:prompt => 'enunciar', :answer => 'to enunciate, to state')
Question.create(:prompt => 'enviar', :answer => 'to send')
Question.create(:prompt => 'envolver', :answer => 'to wrap up')
Question.create(:prompt => 'equivocarse', :answer => 'to be mistaken')
Question.create(:prompt => 'erguir', :answer => 'to raise, to stand up straight')
Question.create(:prompt => 'errar', :answer => 'to err, to wander, to roam, to miss')
Question.create(:prompt => 'escoger', :answer => 'to choose, to select')
Question.create(:prompt => 'escribir', :answer => 'to write')
Question.create(:prompt => 'advertir', :answer => 'to advise, to give notice, to give warning, to take notice of, to warn')
Question.create(:prompt => 'afeitarse', :answer => 'to shave oneself')
Question.create(:prompt => 'agarrar', :answer => 'to grasp, to obtain, to seize, to catch, to clutch, to come upon')
Question.create(:prompt => 'agitar', :answer => 'to agitate, to wave, to shake up, to stir')
Question.create(:prompt => 'agotar', :answer => 'to exhaust, to use up')
Question.create(:prompt => 'agradar', :answer => 'to please, to be pleasing')
Question.create(:prompt => 'agradecer', :answer => 'to thank, to be thankful for')
Question.create(:prompt => 'agrandar', :answer => 'to enlarge, to grow larger, to increase')
Question.create(:prompt => 'agravar', :answer => 'to aggravate, to make worse')
Question.create(:prompt => 'agregar', :answer => 'to add, to collect, to gather, to aggregate, to collate')
Question.create(:prompt => 'agrupar', :answer => 'to group')
Question.create(:prompt => 'aguardar', :answer => 'to expect, to wait for')
Question.create(:prompt => 'ahorrar', :answer => 'to economize, to save')
Question.create(:prompt => 'alcanzar', :answer => 'to reach, to overtake')
Question.create(:prompt => 'alegrarse', :answer => 'to be glad, to rejoice')
Question.create(:prompt => 'almorzar', :answer => 'to lunch, to have lunch')
Question.create(:prompt => 'alquilar', :answer => 'to hire, to rent')
Question.create(:prompt => 'alumbrar', :answer => 'to illuminate, to light, to enlighten')
Question.create(:prompt => 'alumbrarse', :answer => 'to be (get) high, to get tipsy, to become lively (from liquor)')
Question.create(:prompt => 'alzar', :answer => 'to heave, to lift, to pick up, to raise (prices)')
Question.create(:prompt => 'amar', :answer => 'to love')
Question.create(:prompt => 'andar', :answer => 'to walk')
Question.create(:prompt => 'anunciar', :answer => 'to announce, to foretell, to proclaim')
Question.create(:prompt => 'apagar', :answer => 'to put out (flame, fire), to extinguish, to turn off (flame, fire, light)')
Question.create(:prompt => 'aparecer', :answer => 'to appear, to show up')
Question.create(:prompt => 'aplaudir', :answer => 'to applaud')
Question.create(:prompt => 'apoderarse', :answer => 'to take power, to take possession')
Question.create(:prompt => 'apreciar', :answer => 'to appreciate, to appraise, to esteem')
Question.create(:prompt => 'aprender', :answer => 'to learn')
Question.create(:prompt => 'apresurarse', :answer => 'to hasten, to hurry, to rush')
Question.create(:prompt => 'aprobar', :answer => 'to approve, to pass a test')
Question.create(:prompt => 'aprovecharse', :answer => 'to take advantage, to avail oneself')
Question.create(:prompt => 'apurarse', :answer => 'to fret, to grieve, to worry')
Question.create(:prompt => 'arrancar', :answer => 'to root up (out), to pull up (out), to tear off (away), to snatch')
Question.create(:prompt => 'arreglar', :answer => 'to fix, to arrange, to adjust, to regulate, to settle, to repair')
Question.create(:prompt => 'arrojar', :answer => 'to fling, to hurl, to throw')
Question.create(:prompt => 'articular', :answer => 'to articulate, to pronounce distinctly')
Question.create(:prompt => 'asegurar', :answer => 'to assure, to affirm, to assert, to insure')
Question.create(:prompt => 'asir', :answer => 'to seize, to grasp')
Question.create(:prompt => 'asistir', :answer => 'to attend, to assist, to be present')
Question.create(:prompt => 'asustarse', :answer => 'to be frightened, to be scared')
Question.create(:prompt => 'atacar', :answer => 'to attack')
Question.create(:prompt => 'atenerse', :answer => 'to rely on, to depend on')
Question.create(:prompt => 'atraer', :answer => 'to attract, to allure, to charm')
Question.create(:prompt => 'atravesar', :answer => 'to cross, to go through, to run through')
Question.create(:prompt => 'atreverse', :answer => 'to dare, to venture')
Question.create(:prompt => 'avanzar', :answer => 'to advance')
Question.create(:prompt => 'averiguar', :answer => 'to find out, to inquire, to investigate')
Question.create(:prompt => 'ayudar', :answer => 'to help, to aid, to assist')
Question.create(:prompt => 'bailar', :answer => 'to dance')
Question.create(:prompt => 'bajar', :answer => 'to lower, to let down, to come down, to go down, to descend')
Question.create(:prompt => 'balbucear', :answer => 'to stammer, to hesitate in speech')
Question.create(:prompt => 'barrer', :answer => 'to sweep, to whisk')
Question.create(:prompt => 'bastar', :answer => 'to be enough, to be sufficient, to suffice')
Question.create(:prompt => 'bautizar', :answer => 'to baptize, to christen')
Question.create(:prompt => 'beber', :answer => 'to drink')
Question.create(:prompt => 'bendecir', :answer => 'to bless, to consecrate')
Question.create(:prompt => 'borrar', :answer => 'to erase, to cross out')
Question.create(:prompt => 'bostezar', :answer => 'to yawn, to gape')
Question.create(:prompt => 'botar', :answer => 'to fling, to cast (away), to throw (away), to launch')
Question.create(:prompt => 'broncear', :answer => 'to bronze, to tan')
Question.create(:prompt => 'bullir', :answer => 'to boil, to bustle, to hustle, to stir')
Question.create(:prompt => 'burlarse', :answer => 'to make fun of, to poke fun at, to ridicule')
Question.create(:prompt => 'buscar', :answer => 'to look for, to seek')
Question.create(:prompt => 'caber', :answer => 'to be contained, to fit into')
Question.create(:prompt => 'caer', :answer => 'to fall')
Question.create(:prompt => 'caerse', :answer => 'to fall, to fall down, to tumble')
Question.create(:prompt => 'calentar', :answer => 'to heat (up), to warm (up)')
Question.create(:prompt => 'callarse', :answer => 'to be silent, to keep quiet')
Question.create(:prompt => 'calzar', :answer => 'to shoe, to wear (shoes), to put on (shoes)')
Question.create(:prompt => 'cambiar', :answer => 'to change')
Question.create(:prompt => 'caminar', :answer => 'to walk, to move along')
Question.create(:prompt => 'casarse', :answer => 'to get married, to marry')
Question.create(:prompt => 'cansarse', :answer => 'to become tired, to become weary, to get tired')
Question.create(:prompt => 'cantar', :answer => 'to sing')
Question.create(:prompt => 'caracterizar', :answer => 'to characterize')
Question.create(:prompt => 'cargar', :answer => 'to load, to burden')
Question.create(:prompt => 'cenar', :answer => 'to have supper, to eat supper')
Question.create(:prompt => 'cepillar', :answer => 'to brush')
Question.create(:prompt => 'cerrar', :answer => 'to close')
Question.create(:prompt => 'certificar', :answer => 'to certify, to register (a letter), to attest')
Question.create(:prompt => 'charlar', :answer => 'to chat, to prattle')
Question.create(:prompt => 'chistar', :answer => 'to mumble, to mutter')
Question.create(:prompt => 'chupar', :answer => 'to suck')
Question.create(:prompt => 'cocinar', :answer => 'to cook')
Question.create(:prompt => 'coger', :answer => 'to seize, to take, to grasp, to grab, to catch')
Question.create(:prompt => 'colegir', :answer => 'to collect')
Question.create(:prompt => 'colgar', :answer => 'to hang (up)')
Question.create(:prompt => 'colocar', :answer => 'to put, to place')
Question.create(:prompt => 'comenzar', :answer => 'to begin, to commence, to start')
Question.create(:prompt => 'comer', :answer => 'to eat')
Question.create(:prompt => 'abatir', :answer => 'to knock down, to overthrow, to throw down')
Question.create(:prompt => 'abrasar', :answer => 'to burn, to set on fire')
Question.create(:prompt => 'abrazar', :answer => 'to embrace, to hug; to clamp')
Question.create(:prompt => 'abrir', :answer => 'to open')
Question.create(:prompt => 'absolver', :answer => 'to absolve, to acquit')
Question.create(:prompt => 'abstenerse', :answer => 'to abstain')
Question.create(:prompt => 'aburrir', :answer => 'to annoy, to bore, to vex')
Question.create(:prompt => 'aburrirse', :answer => 'to be bored, to grow tired, to grow weary')
Question.create(:prompt => 'acabar', :answer => 'to finish, to end, to complete')
Question.create(:prompt => 'acelerar', :answer => 'to accelerate, to speed, to hasten, to hurry')
Question.create(:prompt => 'aceptar', :answer => 'to accept')
Question.create(:prompt => 'acercar', :answer => 'to bring near, to place near')
Question.create(:prompt => 'acercarse', :answer => 'to approach, to draw near')
Question.create(:prompt => 'acertar', :answer => 'to hit the mark, to hit upon, to do (something) right, to succeed in, to guess right')
Question.create(:prompt => 'aclamar', :answer => 'to acclaim, to applaud, to shout, to hail')
Question.create(:prompt => 'aclarar', :answer => 'to explain, to clarify, to make clear, to rinse, to clear')
Question.create(:prompt => 'aconsejar', :answer => 'to advise, to counsel')
Question.create(:prompt => 'acordar', :answer => 'to agree (upon)')
Question.create(:prompt => 'acordarse', :answer => 'to remember')
Question.create(:prompt => 'acostarse', :answer => 'to go to bed, to lie down')
Question.create(:prompt => 'acostumbrar', :answer => 'to be accustomed')
Question.create(:prompt => 'acuchillar', :answer => 'to knife, to cut, to flash, to cut open')
Question.create(:prompt => 'acudir', :answer => 'to attend, to be present frequently, to respond (to a call), to come to the rescue')
Question.create(:prompt => 'acusar', :answer => 'to accuse')
Question.create(:prompt => 'adelantar', :answer => 'to advance, to keep on, to progress, to go ahead')
Question.create(:prompt => 'adelantarse', :answer => 'to go forward, to go ahead, to move ahead, to take the lead')
Question.create(:prompt => 'adivinar', :answer => 'to divine, to foretell, to guess')
Question.create(:prompt => 'admirar', :answer => 'to admire')
Question.create(:prompt => 'admitir', :answer => 'to admit, to grant, to permit')
Question.create(:prompt => 'adoptar', :answer => 'to adopt')
Question.create(:prompt => 'adorar', :answer => 'to adore, to worship')
Question.create(:prompt => 'adquirir', :answer => 'to acquire, to get, to obtain')
Question.create(:prompt => 'Who is this person?', :answer => 'Mark Mcbride', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_024.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Peter Pascale', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_008.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Edward Peterson', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_029.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Elliott Trevino', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_020.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Diana Stepner', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_002.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Allan Stewart', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_010.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Richard Gay', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_013.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Dimitri Hammond', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_033.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Jason Craft', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_012.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'James Setaro', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_022.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Carl Brasic', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_017.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Ramanujan Iyengar', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_027.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Vishal Kapoor', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_037.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Mandy Figueroa', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_035.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Shawn Hunter', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_032.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Arti Sharma', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_004.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Joseph Rossi', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_011.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Phillip Hazur', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_018.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Jaume Sole', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_005.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Gary Bisaga', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_014.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Barbara Hoag', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_019.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Burton Perkins', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_038.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Ira Nemirovsky', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_028.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Jeffrey Morris', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_034.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Jonpaul Aragon', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_030.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Cory Goleman', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_023.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Marianne Phinney Liapis', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_025.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Karyn Crouse', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_021.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Peter Van Tienen', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_036.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Krishnan Krishnaiyer', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_039.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Simon Wilkinson', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_006.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Turab Fatakdawala', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_009.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Tammy Lakes', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_015.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Shashikant Kharat', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_007.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Marc Hamilton', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_016.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Keith Chasse', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_031.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Nathan Ericson', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_003.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Ron Lancaster', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display_026.png' ,:questionset_id=>1)
Question.create(:prompt => 'Who is this person?', :answer => 'Andrew Elmhorst', :prompt_image => 'neo/2011-pearson-technology-summit_files/profile-image-display.png' ,:questionset_id=>1)
